"""add_email_delivery_logs_table

Revision ID: 3c99f9415dcc
Revises: b73646cee5b2
Create Date: 2025-10-12 13:50:09.728010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = '3c99f9415dcc'
down_revision: Union[str, None] = 'b73646cee5b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    # Check if table already exists (idempotent migration)
    if 'email_delivery_logs' not in inspector.get_table_names():
        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('email_delivery_logs',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('recipient', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column('template_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column('sent_at', sa.DateTime(), nullable=False),
        sa.Column('delivery_status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.Column('context_data', sa.TEXT(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('email_delivery_logs', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_email_delivery_logs_delivery_status'), ['delivery_status'], unique=False)
            batch_op.create_index(batch_op.f('ix_email_delivery_logs_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_email_delivery_logs_recipient'), ['recipient'], unique=False)

        # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    # Check if table exists before trying to drop it (idempotent migration)
    if 'email_delivery_logs' in inspector.get_table_names():
        # ### commands auto generated by Alembic - please adjust! ###
        with op.batch_alter_table('email_delivery_logs', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_email_delivery_logs_recipient'))
            batch_op.drop_index(batch_op.f('ix_email_delivery_logs_id'))
            batch_op.drop_index(batch_op.f('ix_email_delivery_logs_delivery_status'))

        op.drop_table('email_delivery_logs')
        # ### end Alembic commands ###
