"""Add workspace_id to service_account table

Revision ID: 76de831c80a4
Revises: 48a9b6fddf7c
Create Date: 2025-10-12 07:10:33.574842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = '76de831c80a4'
down_revision: Union[str, None] = '48a9b6fddf7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###

    # For SQLite, we can't use ALTER COLUMN to change nullable
    # Check if service_account table exists and has data
    inspector = Inspector.from_engine(conn)
    has_existing_data = False

    if 'service_account' in inspector.get_table_names():
        result = conn.execute(sa.text("SELECT COUNT(*) FROM service_account"))
        count = result.scalar()
        has_existing_data = count > 0

    # Check if workspace_id column already exists
    columns = [col['name'] for col in inspector.get_columns('service_account')] if 'service_account' in inspector.get_table_names() else []

    if 'workspace_id' in columns:
        # Column already exists, skip migration
        return

    if has_existing_data:
        # Step 1: Add column as nullable first for existing data
        op.add_column('service_account', sa.Column('workspace_id', sa.Uuid(), nullable=True))

        # Step 2: Get first workspace as default
        result = conn.execute(sa.text("SELECT id FROM workspace LIMIT 1"))
        default_workspace = result.fetchone()

        if default_workspace:
            # Assign existing service accounts to default workspace
            conn.execute(
                sa.text("UPDATE service_account SET workspace_id = :workspace_id WHERE workspace_id IS NULL"),
                {"workspace_id": str(default_workspace[0])}
            )

        # Step 3: For SQLite, recreate table with NOT NULL constraint
        # Use batch_alter_table to rebuild the table
        with op.batch_alter_table('service_account', schema=None, copy_from=None, recreate='always') as batch_op:
            batch_op.alter_column('workspace_id', existing_type=sa.Uuid(), nullable=False)
            batch_op.create_index(batch_op.f('ix_service_account_workspace_id'), ['workspace_id'], unique=False)
            batch_op.create_foreign_key('fk_service_account_workspace_id', 'workspace', ['workspace_id'], ['id'])
    else:
        # No existing data, add column with NOT NULL and constraints
        op.add_column('service_account', sa.Column('workspace_id', sa.Uuid(), nullable=False))
        op.create_index(op.f('ix_service_account_workspace_id'), 'service_account', ['workspace_id'], unique=False)
        op.create_foreign_key('fk_service_account_workspace_id', 'service_account', 'workspace', ['workspace_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_service_account_workspace_id', 'service_account', type_='foreignkey')
    op.drop_index(op.f('ix_service_account_workspace_id'), table_name='service_account')
    op.drop_column('service_account', 'workspace_id')
    # ### end Alembic commands ###
