"""Add email field to user table

Revision ID: b73646cee5b2
Revises: 75014ffc833e
Create Date: 2025-10-12 13:06:39.231195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.engine.reflection import Inspector
from langflow.utils import migration


# revision identifiers, used by Alembic.
revision: str = 'b73646cee5b2'
down_revision: Union[str, None] = '75014ffc833e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)

    # ### commands auto generated by Alembic - please adjust! ###
    # Check if email column already exists before adding it
    user_columns = [col['name'] for col in inspector.get_columns('user')]

    with op.batch_alter_table('user', schema=None) as batch_op:
        if 'email' not in user_columns:
            batch_op.add_column(sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
            batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)

    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.NUMERIC(),
               type_=sa.Uuid(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workspace', schema=None) as batch_op:
        batch_op.alter_column('created_by',
               existing_type=sa.Uuid(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_column('email')

    # ### end Alembic commands ###
