"""Add RBAC tables

Revision ID: c62fe238bf8b
Revises: fd531f8868b1
Create Date: 2025-11-05 00:00:00.000000

"""

from typing import Optional, Sequence, Union
from uuid import uuid4

import sqlalchemy as sa
from alembic import op
from loguru import logger
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c62fe238bf8b"
down_revision: Union[str, None] = "fd531f8868b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create RBAC tables in the correct dependency order."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Create role table first (no dependencies)
    op.create_table(
        "role",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
        sa.UniqueConstraint("id", name=op.f("uq_role_id")),
    )
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_role_name"), ["name"], unique=True)

    # 2. Create permission table (no dependencies)
    op.create_table(
        "permission",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("scope_type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permission")),
        sa.UniqueConstraint("id", name=op.f("uq_permission_id")),
    )
    with op.batch_alter_table("permission", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_permission_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_permission_scope_type"), ["scope_type"], unique=False)

    # 3. Create role_permission junction table (depends on role and permission)
    op.create_table(
        "role_permission",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("role_id", sa.String(), nullable=False),
        sa.Column("permission_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permission.id"],
            name=op.f("fk_role_permission_permission_id_permission"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
            name=op.f("fk_role_permission_role_id_role"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_permission")),
        sa.UniqueConstraint("role_id", "permission_id", name="unique_role_permission"),
        sa.UniqueConstraint("id", name=op.f("uq_role_permission_id")),
    )
    with op.batch_alter_table("role_permission", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_role_permission_permission_id"), ["permission_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_role_permission_role_id"), ["role_id"], unique=False)

    # 4. Create user_role_assignment table (depends on user and role)
    op.create_table(
        "user_role_assignment",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("role_id", sa.String(), nullable=False),
        sa.Column("scope_type", sa.String(), nullable=False),
        sa.Column("scope_id", sa.String(), nullable=True),
        sa.Column("is_immutable", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["user.id"],
            name=op.f("fk_user_role_assignment_created_by_user"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
            name=op.f("fk_user_role_assignment_role_id_role"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_user_role_assignment_user_id_user"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_role_assignment")),
        sa.UniqueConstraint("user_id", "role_id", "scope_type", "scope_id", name="unique_user_role_scope"),
        sa.UniqueConstraint("id", name=op.f("uq_user_role_assignment_id")),
    )
    with op.batch_alter_table("user_role_assignment", schema=None) as batch_op:
        batch_op.create_index("idx_scope_lookup", ["user_id", "scope_type", "scope_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_role_assignment_role_id"), ["role_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_role_assignment_scope_id"), ["scope_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_role_assignment_scope_type"), ["scope_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_user_role_assignment_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###

    # Seed RBAC data: roles, permissions, and role-permission mappings
    logger.info("Seeding RBAC data...")
    connection = op.get_bind()

    # Define predefined roles
    roles = [
        {"id": str(uuid4()), "name": "Admin", "description": "Full access to all resources and actions across all scopes", "is_system": True},
        {"id": str(uuid4()), "name": "Owner", "description": "Full CRUD access to assigned scope (Flow or Project)", "is_system": True},
        {"id": str(uuid4()), "name": "Editor", "description": "Create, Read, and Update access to assigned scope (no Delete)", "is_system": True},
        {"id": str(uuid4()), "name": "Viewer", "description": "Read-only access to assigned scope", "is_system": True},
    ]

    # Insert roles
    for role in roles:
        connection.execute(text(
            "INSERT INTO role (id, name, description, is_system) VALUES (:id, :name, :description, :is_system)"
        ), role)
        logger.debug(f"Created role: {role['name']}")

    # Define predefined permissions (using generic names that are reused across scope types)
    permissions = [
        {"id": str(uuid4()), "name": "Create", "scope_type": "Flow", "description": "Create new flows"},
        {"id": str(uuid4()), "name": "Read", "scope_type": "Flow", "description": "View flows, execute flows, save flows, export flows, download flows"},
        {"id": str(uuid4()), "name": "Update", "scope_type": "Flow", "description": "Modify existing flows, import flows"},
        {"id": str(uuid4()), "name": "Delete", "scope_type": "Flow", "description": "Delete flows"},
        {"id": str(uuid4()), "name": "Create", "scope_type": "Project", "description": "Create new projects"},
        {"id": str(uuid4()), "name": "Read", "scope_type": "Project", "description": "View projects and their contents"},
        {"id": str(uuid4()), "name": "Update", "scope_type": "Project", "description": "Modify existing projects, import projects"},
        {"id": str(uuid4()), "name": "Delete", "scope_type": "Project", "description": "Delete projects"},
    ]

    # Insert permissions
    for perm in permissions:
        connection.execute(text(
            "INSERT INTO permission (id, name, scope_type, description) VALUES (:id, :name, :scope_type, :description)"
        ), perm)
        logger.debug(f"Created permission: {perm['name']}")

    # Define role-permission mappings (using tuples of (permission_name, scope_type))
    role_permission_mappings = {
        "Admin": [
            ("Create", "Flow"), ("Read", "Flow"), ("Update", "Flow"), ("Delete", "Flow"),
            ("Create", "Project"), ("Read", "Project"), ("Update", "Project"), ("Delete", "Project"),
        ],
        "Owner": [
            ("Create", "Flow"), ("Read", "Flow"), ("Update", "Flow"), ("Delete", "Flow"),
            ("Create", "Project"), ("Read", "Project"), ("Update", "Project"), ("Delete", "Project"),
        ],
        "Editor": [
            ("Create", "Flow"), ("Read", "Flow"), ("Update", "Flow"),
            ("Create", "Project"), ("Read", "Project"), ("Update", "Project"),
        ],
        "Viewer": [
            ("Read", "Flow"), ("Read", "Project"),
        ],
    }

    # Create role-permission mappings
    for role_name, permission_tuples in role_permission_mappings.items():
        role_id = connection.execute(text("SELECT id FROM role WHERE name = :name"), {"name": role_name}).fetchone()[0]

        for perm_name, scope_type in permission_tuples:
            # Query by both name AND scope_type since permission names are not unique
            perm_id = connection.execute(
                text("SELECT id FROM permission WHERE name = :name AND scope_type = :scope_type"),
                {"name": perm_name, "scope_type": scope_type}
            ).fetchone()[0]

            connection.execute(text(
                "INSERT INTO role_permission (id, role_id, permission_id) VALUES (:id, :role_id, :permission_id)"
            ), {"id": str(uuid4()), "role_id": role_id, "permission_id": perm_id})

        logger.debug(f"Created {len(permission_tuples)} permission mappings for role: {role_name}")

    logger.info("RBAC seed data created successfully")


def downgrade() -> None:
    """Drop RBAC tables in reverse dependency order."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 4. Drop user_role_assignment first (has foreign keys to role and user)
    with op.batch_alter_table("user_role_assignment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_role_assignment_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_role_assignment_scope_type"))
        batch_op.drop_index(batch_op.f("ix_user_role_assignment_scope_id"))
        batch_op.drop_index(batch_op.f("ix_user_role_assignment_role_id"))
        batch_op.drop_index("idx_scope_lookup")

    op.drop_table("user_role_assignment")

    # 3. Drop role_permission (has foreign keys to role and permission)
    with op.batch_alter_table("role_permission", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_role_permission_role_id"))
        batch_op.drop_index(batch_op.f("ix_role_permission_permission_id"))

    op.drop_table("role_permission")

    # 2. Drop permission (no dependencies)
    with op.batch_alter_table("permission", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_permission_scope_type"))
        batch_op.drop_index(batch_op.f("ix_permission_name"))

    op.drop_table("permission")

    # 1. Drop role last (no dependencies)
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_role_name"))

    op.drop_table("role")

    # ### end Alembic commands ###
