"""Add RBAC tables: Role, Permission, RolePermission, UserRoleAssignment.

Revision ID: d6c803ed2d15
Revises: 3162e83e485f
Create Date: 2025-11-01 11:26:37.030220

"""
# ruff: noqa: INP001, F841

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6c803ed2d15"
down_revision: str | None = "3162e83e485f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permission",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Enum("CREATE", "READ", "UPDATE", "DELETE", name="permissionenum"), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("permission", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_permission_name"), ["name"], unique=True)

    op.create_table(
        "role",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.Enum("ADMIN", "OWNER", "EDITOR", "VIEWER", name="roleenum"), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_role_name"), ["name"], unique=True)

    op.create_table(
        "rolepermission",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("permission_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permission.id"]),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role_id", "permission_id", name="unique_role_permission"),
    )
    with op.batch_alter_table("rolepermission", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_rolepermission_permission_id"), ["permission_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_rolepermission_role_id"), ["role_id"], unique=False)

    op.create_table(
        "userroleassignment",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("scope_type", sa.Enum("GLOBAL", "PROJECT", "FLOW", name="scopetypeenum"), nullable=False),
        sa.Column("scope_id", sa.Uuid(), nullable=True),
        sa.Column("is_immutable", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "scope_type", "scope_id", name="unique_user_scope"),
    )
    with op.batch_alter_table("userroleassignment", schema=None) as batch_op:
        batch_op.create_index("ix_user_scope", ["user_id", "scope_type", "scope_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_userroleassignment_role_id"), ["role_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_userroleassignment_scope_id"), ["scope_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_userroleassignment_scope_type"), ["scope_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_userroleassignment_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    conn = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("userroleassignment", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_userroleassignment_user_id"))
        batch_op.drop_index(batch_op.f("ix_userroleassignment_scope_type"))
        batch_op.drop_index(batch_op.f("ix_userroleassignment_scope_id"))
        batch_op.drop_index(batch_op.f("ix_userroleassignment_role_id"))
        batch_op.drop_index("ix_user_scope")

    op.drop_table("userroleassignment")
    with op.batch_alter_table("rolepermission", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rolepermission_role_id"))
        batch_op.drop_index(batch_op.f("ix_rolepermission_permission_id"))

    op.drop_table("rolepermission")
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_role_name"))

    op.drop_table("role")
    with op.batch_alter_table("permission", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_permission_name"))

    op.drop_table("permission")
    # ### end Alembic commands ###
